version: "3.1"

services:

  proxy:
    image: traefik:latest
    container_name: proxy
    command: --api --docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    networks:
      - intranet
    labels:
      - "traefik.backend=proxy"
      - "traefik.frontend.rule=Host:proxy.local"
      - "traefik.frontend.entryPoints=https"
      - "traefik.docker.network=intranet"
      - "traefik.port=8080"

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: php:7.2-apache
    container_name: api
    volumes:
      - ./:/var/www/html/
      - ./docker/api/default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - intranet
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:api.local"
      - "traefik.frontend.entryPoints=https"
      - "traefik.docker.network=intranet"
      - "traefik.port=80"
    depends_on:
      - ${DB_HOST}

  database:
    image: postgres:10
    container_name: ${DB_HOST}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./docker/api/waiter.sh:/scripts/waiter.sh
    networks:
      - intranet
    labels:
      - "traefik.enable=false"

networks:

  intranet:
    driver: bridge
