version: "3.1"

services:
  proxy:
    image: traefik:latest
    container_name: proxy
    command: --api --docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
    networks:
      - default
    labels:
      - "traefik.backend=proxy"
      - "traefik.frontend.rule=Host:proxy.local"
      - "traefik.docker.network=default"
      - "traefik.port=8080"
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    image: php:7.2-apache
    container_name: api
    volumes:
      - ./:/var/www/html/
      - ./docker/api/default.conf:/etc/apache2/sites-enabled/000-default.conf
    networks:
      - default
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:api.local"
      - "traefik.docker.network=default"
      - "traefik.port=80"
  database:
    image: postgres:10
    container_name: database
    environment: 
      POSTGRES_USER: web
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: hotels
    ports:
      - 5432:5432
    networks:
      - default
    labels:
      - "traefik.backend=database"
      - "traefik.frontend.rule=Host:database.local"
      - "traefik.docker.network=default"
      - "traefik.port=5432"
networks:
  default:
    driver: bridge
