logLevel = "DEBUG"
defaultEntryPoints = ["http"]

[entryPoints]

  [entryPoints.http]
  address = ":80"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "docker.local"
watch = true
exposedByDefault = false
